/**
 * What a CUSTOMER may write to their own customization, and what they never
 * may. Shared by POST /api/customizations (create) and
 * PATCH /api/customizations/[id] (update).
 *
 * Customer-editable design state:
 *   values, editorState / renderData, uploadedFiles, selectedOptions,
 *   activePage, cartItemId (only their own cart line), status (draft,
 *   in_cart, archived), clientRevision (the editor's save ordering number).
 *
 * Server-managed (rejected when a request tries to set them):
 *   userId, orderId, status "ordered", printFiles, previewImages (non-empty),
 *   assetReferences (always recomputed on the server), and — for an existing
 *   design — productId, templateId and templateVersion.
 */

import { OPTION_GROUPS } from "@/lib/orders/pricing-resolver";
import { parseClientRevision } from "@/lib/customizer/save-revision";

export const CUSTOMER_STATUSES = new Set(["draft", "in_cart", "archived"]);

const OPTION_KEYS = new Set([...OPTION_GROUPS.map((group) => group.key), "logo", "quantity", "customQty", "activePage"]);

export type CustomerWriteResult = { ok: true; body: Record<string, any> } | { ok: false; status: number; error: string };

const isEmptyObject = (value: unknown) =>
  value === undefined || value === null || (typeof value === "object" && !Array.isArray(value) && Object.keys(value as object).length === 0);

/**
 * Option choices are stored as the customer's preference; they are priced
 * only at checkout (by identity, against server data). Here only their SHAPE
 * is enforced so the column can never hold arbitrary nested data.
 */
export function sanitizeSelectedOptionsShape(value: unknown): Record<string, string | number | boolean> | null {
  if (value === undefined) return null;
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  const out: Record<string, string | number | boolean> = {};
  for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
    if (!OPTION_KEYS.has(key)) continue;
    if (typeof entry === "string") out[key] = entry.slice(0, 300);
    else if (typeof entry === "boolean") out[key] = entry;
    else if (typeof entry === "number" && Number.isFinite(entry)) out[key] = entry;
  }
  return out;
}

/**
 * The editor names the account the design ON ITS SCREEN belongs to
 * (`expectedUserId`). On a shared browser the session can change underneath an
 * open editor — another tab signs out and a different customer signs in — and
 * a save still queued in the old page would then be written with the NEW
 * session: a brand-new design would be created in someone else's account. Such
 * a save is refused before anything is read or written. The field is a
 * precondition only; ownership is always the session's user.
 */
export function rejectAccountMismatch(body: unknown, userId: string): Response | null {
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const expected = (body as Record<string, unknown>).expectedUserId;
  if (expected === undefined || expected === null || expected === "") return null;
  if (String(expected) === String(userId)) return null;
  return Response.json(
    { ok: false, code: "account-changed", error: "You are now signed in to a different account. This design was not saved to it." },
    { status: 409 },
  );
}

export function prepareCustomerWrite(
  body: Record<string, any>,
  existing: { productId: string; templateId: string; templateVersion: number } | null,
): CustomerWriteResult {
  if (!body || typeof body !== "object" || Array.isArray(body)) {
    return { ok: false, status: 400, error: "The request body is invalid." };
  }
  if (body.userId !== undefined || body.user_id !== undefined) {
    return { ok: false, status: 400, error: "The owner of a design is set by Husnalogy." };
  }
  if (body.orderId || body.order_id) {
    return { ok: false, status: 400, error: "A design is linked to an order only by checkout." };
  }
  if (!isEmptyObject(body.printFiles) || !isEmptyObject(body.previewImages)) {
    return { ok: false, status: 400, error: "Production and preview files are generated by Husnalogy." };
  }
  if (body.status !== undefined && !CUSTOMER_STATUSES.has(String(body.status))) {
    return { ok: false, status: 400, error: "A design cannot be given that status." };
  }
  if (existing) {
    const changesIdentity =
      (body.productId !== undefined && String(body.productId) !== existing.productId) ||
      (body.templateId !== undefined && String(body.templateId) !== existing.templateId) ||
      (body.templateVersion !== undefined && Number(body.templateVersion) !== existing.templateVersion);
    if (changesIdentity) {
      return { ok: false, status: 400, error: "A saved design cannot be moved to another product or template. Start a new design instead." };
    }
  }

  const clean: Record<string, any> = {};
  for (const key of ["values", "editorState", "renderData", "uploadedFiles", "activePage", "cartItemId", "status"]) {
    if (body[key] !== undefined) clean[key] = body[key];
  }
  if (body.clientRevision !== undefined) {
    const revision = parseClientRevision(body.clientRevision);
    if (revision === null) return { ok: false, status: 400, error: "The design revision is invalid." };
    clean.clientRevision = revision;
  }
  const options = sanitizeSelectedOptionsShape(body.selectedOptions);
  if (options) clean.selectedOptions = options;
  if (!existing) {
    clean.productId = String(body.productId || "");
    clean.templateId = String(body.templateId || "");
    clean.templateVersion = Number(body.templateVersion) || 0;
  }
  return { ok: true, body: clean };
}
