/**
 * Which images may appear in public sharing metadata (og:image, twitter:image,
 * the sitemap's image entries).
 *
 * A share preview is fetched by external crawlers without a session and
 * cached by them for a long time, so only durable, public catalogue imagery
 * qualifies:
 *  - site-relative files the site ships in /public (brand and catalogue art);
 *  - this Supabase project's PUBLIC catalogue buckets, without a query string.
 *
 * Everything else is rejected: signed storage URLs (they expire and carry a
 * token), private buckets (customer uploads, production files, renders),
 * other hosts, API routes and data/blob URLs. A rejected image falls back to
 * the branded default rather than to whatever the product happened to hold.
 */

import { getSiteUrl } from "@/lib/site-url";

/** The branded default preview, generated by scripts/generate-social-image.mjs. */
export const DEFAULT_SHARE_IMAGE = {
  url: "/og/husnalogy-share.png",
  width: 1200,
  height: 630,
  type: "image/png",
  alt: "Husnalogy wordmark with the line: wedding invitations, stationery and personalized gifts",
} as const;

export type ShareImage = {
  url: string;
  alt: string;
  width?: number;
  height?: number;
  type?: string;
};

const PUBLIC_CATALOGUE_BUCKETS = ["product-images", "product-mockups", "site-assets"];
const PUBLIC_LOCAL_PREFIXES = ["/images/", "/og/", "/Brand Kit/", "/icons/"];

type ShareImageEnv = { siteUrl?: string; supabaseUrl?: string };

function supabaseHost(supabaseUrl: string): string {
  try {
    return new URL(String(supabaseUrl || "").replace(/\/rest\/v1\/?$/i, "")).host.toLowerCase();
  } catch {
    return "";
  }
}

/**
 * The absolute, publicly fetchable URL for an image, or null when the image
 * must not be used in sharing metadata.
 */
export function toPublicShareImageUrl(source: unknown, env: ShareImageEnv = {}): string | null {
  const value = typeof source === "string" ? source.trim() : "";
  if (!value) return null;
  const siteUrl = env.siteUrl ?? getSiteUrl();

  if (value.startsWith("/") && !value.startsWith("//")) {
    let path: string;
    try {
      path = decodeURI(value);
    } catch {
      return null;
    }
    if (path.includes("?") || path.includes("#") || path.includes("..") || path.includes("\\")) return null;
    if (!PUBLIC_LOCAL_PREFIXES.some((prefix) => path.startsWith(prefix))) return null;
    return `${siteUrl}${encodeURI(path)}`;
  }

  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return null;
  }
  const host = supabaseHost(env.supabaseUrl ?? process.env.NEXT_PUBLIC_SUPABASE_URL ?? "");
  if (url.protocol !== "https:" || !host || url.host.toLowerCase() !== host) return null;
  if (url.username || url.password || url.search || url.hash) return null;
  const isPublicBucket = PUBLIC_CATALOGUE_BUCKETS.some((bucket) =>
    url.pathname.startsWith(`/storage/v1/object/public/${bucket}/`),
  );
  if (!isPublicBucket || url.pathname.includes("..")) return null;
  return url.href;
}

function imageSource(value: any): string {
  if (!value) return "";
  if (typeof value === "string") return value;
  if (typeof value === "object") return value.src || value.url || value.image || value.imageUrl || value.mockup || value.thumbnail || "";
  return "";
}

/**
 * The product's public imagery in the order the storefront presents it
 * (main mockup first, then gallery images), filtered to shareable URLs.
 */
export function productShareImageUrls(product: any, env: ShareImageEnv = {}): string[] {
  if (!product) return [];
  const candidates = [
    product.mainMockup,
    product.mockupImage,
    product.mockup,
    ...(Array.isArray(product.mockups) ? product.mockups : []),
    product.mainImage,
    product.thumbnail,
    product.image,
    ...(Array.isArray(product.images) ? product.images : []),
  ].map(imageSource);
  const urls: string[] = [];
  for (const candidate of candidates) {
    const url = toPublicShareImageUrl(candidate, env);
    if (url && !urls.includes(url)) urls.push(url);
  }
  return urls;
}
