"use client";

import { isValidQRValue, qrContrastRatio } from "@/lib/customizer/v2/qr";
import { createGridSlotsFromPreset, GRID_PRESETS } from "@/lib/customizer/v2/grids";

export default function CustomerObjectToolbar({ layers, onOpacity, onPatch, onArrange, onAlign, onGroup, onUngroup, onDuplicate, onDelete }: any) {
  if (!layers?.length) return null;
  const opacity = Math.round((Number(layers[0]?.opacity) || 0) * 100);
  const qrReadable = layers[0]?.type !== "qrCode" || (isValidQRValue(layers[0].value) && qrContrastRatio(layers[0].foregroundColor || "#303839", layers[0].backgroundColor || "#ffffff") >= 4.5 && Number(layers[0].width) >= 96);
  const button = "min-h-11 shrink-0 rounded-lg border border-[#303839]/10 bg-white px-3 text-[10px] font-extrabold text-[#303839] hover:bg-[#F8F6F1] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D4AF37]";
  return (
    <div role="toolbar" aria-label={`${layers.length} selected objects`} className="pointer-events-auto flex max-w-full items-center gap-1.5 overflow-x-auto rounded-2xl border border-[#303839]/12 bg-white p-2 shadow-[0_14px_38px_rgba(48,56,57,0.16)] [scrollbar-width:none]">
      <span className="shrink-0 rounded-lg bg-[#303839] px-3 py-2 text-[10px] font-extrabold text-white">{layers.length} selected</span>
      {layers.length === 1 && <label className="flex min-h-10 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-3 text-[10px] font-bold"><span>Opacity</span><input type="range" min="0" max="100" step="5" value={opacity} onChange={(event) => onOpacity(Number(event.target.value) / 100)} aria-label="Object opacity" /><output>{opacity}%</output></label>}
      {layers.length === 1 && layers[0].type === "shape" && <><label className="grid min-h-11 shrink-0 grid-cols-[auto_30px] items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>{layers[0].shape === "line" ? "Colour" : "Fill"}</span><input type="color" value={layers[0].shape === "line" ? layers[0].stroke || "#303839" : layers[0].fill || "#F8F6F1"} onChange={(event) => onPatch(layers[0].shape === "line" ? { stroke: event.target.value } : { fill: event.target.value })} className="h-8 w-8 rounded-full" /></label>{layers[0].shape !== "line" && <label className="grid min-h-11 shrink-0 grid-cols-[auto_30px] items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Border</span><input type="color" value={layers[0].stroke || "#303839"} onChange={(event) => onPatch({ stroke: event.target.value })} className="h-8 w-8 rounded-full" /></label>}<label className="flex min-h-11 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>{layers[0].shape === "line" ? "Thickness" : "Width"}</span><input type="range" min="0" max="40" value={layers[0].strokeWidth || 0} onChange={(event) => onPatch({ strokeWidth: Number(event.target.value) })} className="w-16 accent-[#303839]" /></label>{layers[0].shape === "line" && <><select aria-label="Line style" value={layers[0].lineStyle || "solid"} onChange={(event) => onPatch({ lineStyle: event.target.value })} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select><select aria-label="Stroke cap" value={layers[0].lineCap || "round"} onChange={(event) => onPatch({ lineCap: event.target.value })} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="butt">Flat stroke</option><option value="round">Round stroke</option><option value="square">Square stroke</option></select><select aria-label="Line start cap" value={layers[0].lineStartCap || "none"} onChange={(event) => onPatch({ lineStartCap: event.target.value })} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="none">No start cap</option><option value="circle">Start circle</option><option value="arrow">Start arrow</option></select><select aria-label="Line end cap" value={layers[0].lineEndCap || "none"} onChange={(event) => onPatch({ lineEndCap: event.target.value })} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="none">No end cap</option><option value="circle">End circle</option><option value="arrow">End arrow</option></select></>}</>}
      {layers.length === 1 && layers[0].type === "frame" && <><label className="grid min-h-11 shrink-0 grid-cols-[auto_30px] items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Border</span><input type="color" value={layers[0].borderColor || "#303839"} onChange={(event) => onPatch({ borderColor: event.target.value })} className="h-8 w-8 rounded-full" /></label><label className="flex min-h-11 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Border width</span><input type="range" min="0" max="40" value={layers[0].borderWidth || 0} onChange={(event) => onPatch({ borderWidth: Number(event.target.value) })} className="w-16 accent-[#303839]" /></label></>}
      {layers.length === 1 && layers[0].type === "grid" && <>{layers[0].isUserLayer && <select aria-label="Grid layout" defaultValue="" onChange={(event) => { const preset = GRID_PRESETS.find((item) => item.id === event.target.value); if (preset) onPatch({ columns: preset.columns, rows: preset.rows, slots: createGridSlotsFromPreset(preset.id) }); event.currentTarget.value = ""; }} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="" disabled>Change layout</option>{GRID_PRESETS.map((preset) => <option key={preset.id} value={preset.id}>{preset.label}</option>)}</select>}<label className="flex min-h-11 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Gap</span><input type="range" min="0" max="80" value={layers[0].gap || 0} onChange={(event) => onPatch({ gap: Number(event.target.value) })} className="w-16 accent-[#303839]" /></label><label className="flex min-h-11 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Padding</span><input type="range" min="0" max="100" value={layers[0].padding || 0} onChange={(event) => onPatch({ padding: Number(event.target.value) })} className="w-16 accent-[#303839]" /></label><label className="flex min-h-11 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Round</span><input type="range" min="0" max="120" value={layers[0].cornerRadius || 0} onChange={(event) => onPatch({ cornerRadius: Number(event.target.value) })} className="w-16 accent-[#303839]" /></label></>}
      {layers.length === 1 && layers[0].type === "qrCode" && <><label className="flex min-h-11 min-w-56 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>URL</span><input type="url" value={layers[0].value || ""} onChange={(event) => onPatch({ value: event.target.value })} className="h-9 min-w-0 flex-1 rounded-md border border-[#303839]/12 bg-white px-2 text-xs" /></label><label className="grid min-h-11 shrink-0 grid-cols-[auto_30px] items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Code</span><input type="color" value={layers[0].foregroundColor || "#303839"} onChange={(event) => onPatch({ foregroundColor: event.target.value })} className="h-8 w-8 rounded-full" /></label><label className="grid min-h-11 shrink-0 grid-cols-[auto_30px] items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Background</span><input type="color" value={layers[0].backgroundColor || "#ffffff"} onChange={(event) => onPatch({ backgroundColor: event.target.value })} className="h-8 w-8 rounded-full" /></label><label className="flex min-h-11 shrink-0 items-center gap-2 rounded-lg bg-[#F8F6F1] px-2 text-[9px] font-bold"><span>Margin</span><input type="range" min="0" max="12" value={layers[0].margin ?? 4} onChange={(event) => onPatch({ margin: Number(event.target.value) })} className="w-14 accent-[#303839]" /></label><select aria-label="QR error correction" value={layers[0].errorCorrection || "M"} onChange={(event) => onPatch({ errorCorrection: event.target.value })} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="L">Low correction</option><option value="M">Medium correction</option><option value="Q">Quartile correction</option><option value="H">High correction</option></select><select aria-label="QR module style" value={layers[0].moduleStyle || "square"} onChange={(event) => onPatch({ moduleStyle: event.target.value })} className="min-h-11 rounded-lg border border-[#303839]/12 bg-white px-2 text-[10px] font-bold"><option value="square">Square modules</option><option value="rounded">Rounded modules</option></select><span role="status" className={`shrink-0 rounded-lg px-3 py-3 text-[9px] font-extrabold ${qrReadable ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}`}>{qrReadable ? "Readable" : "Improve QR readability"}</span></>}
      {[['bringToFront', 'Front'], ['bringForward', 'Forward'], ['sendBackward', 'Backward'], ['sendToBack', 'Back']].map(([action, label]) => <button key={action} type="button" onClick={() => onArrange(action)} className={button}>{label}</button>)}
      {layers.length > 1 && <select aria-label="Align or distribute selected objects" defaultValue="" onChange={(event) => { if (event.target.value) onAlign(event.target.value); event.currentTarget.value = ""; }} className="min-h-11 shrink-0 rounded-lg border border-[#303839]/12 bg-white px-3 text-[10px] font-extrabold text-[#303839] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D4AF37]"><option value="" disabled>Align &amp; distribute</option><option value="alignLeft">Align left</option><option value="alignCenter">Align centre</option><option value="alignRight">Align right</option><option value="alignTop">Align top</option><option value="alignMiddle">Align middle</option><option value="alignBottom">Align bottom</option>{layers.length > 2 && <><option value="distributeHorizontal">Distribute horizontally</option><option value="distributeVertical">Distribute vertically</option></>}</select>}
      {layers.length > 1 && <button type="button" onClick={onGroup} className={button}>Group</button>}
      {layers.length === 1 && layers[0].type === "group" && <button type="button" onClick={onUngroup} className={button}>Ungroup</button>}
      <button type="button" onClick={onDuplicate} className={button}>Duplicate</button>
      <button type="button" onClick={onDelete} className={`${button} text-red-700`}>Delete</button>
    </div>
  );
}
